const $=(s,p=document)=>p.querySelector(s),$$=(s,p=document)=>[...p.querySelectorAll(s)];
const money=n=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(n)||0);
const defaults={name:'',income:0,payday:1,expenses:[],subscriptions:[],categories:['Moradia','Alimentação','Transporte','Saúde','Lazer','Outros']};
let state=JSON.parse(localStorage.getItem('equilibra-data')||'null')||structuredClone(defaults);
const save=()=>{localStorage.setItem('equilibra-data',JSON.stringify(state));render()};
const toast=t=>{const el=$('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200)};

const observer=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add('visible')),{threshold:.15});
$$('.reveal').forEach(el=>observer.observe(el));

let ticking=false;
function updateScrollMotion(){
 const y=window.scrollY,max=document.documentElement.scrollHeight-innerHeight;
 $('#scrollProgress').style.transform=`scaleX(${Math.min(1,y/max)})`;
 const hero=Math.min(1,y/innerHeight);
 document.documentElement.style.setProperty('--hero-scroll',hero.toFixed(3));
 const story=$('.scroll-story'),rect=story.getBoundingClientRect(),travel=story.offsetHeight-innerHeight;
 const progress=Math.max(0,Math.min(1,-rect.top/travel));
 document.documentElement.style.setProperty('--story',progress.toFixed(3));
 ticking=false;
}
addEventListener('scroll',()=>{if(!ticking){requestAnimationFrame(updateScrollMotion);ticking=true}},{passive:true});
updateScrollMotion();

function openApp(){ $('#app').classList.add('open');document.body.style.overflow='hidden';if(!state.name&&!state.income)openOnboarding() }
function closeApp(){ $('#app').classList.remove('open');document.body.style.overflow='';closeDrawer() }
$$('[data-open-app]').forEach(b=>b.onclick=openApp);$('.back-site').onclick=closeApp;

function openDrawer(html){$('#drawerContent').innerHTML=html;$('#overlay').classList.add('open');$('#drawer').classList.add('open');$('#drawer').setAttribute('aria-hidden','false')}
function closeDrawer(){$('#overlay').classList.remove('open');$('#drawer').classList.remove('open');$('#drawer').setAttribute('aria-hidden','true')}
$('#closeDrawer').onclick=closeDrawer;$('#overlay').onclick=closeDrawer;

function openOnboarding(){
 openDrawer(`<span class="eyebrow dark">Primeiros passos</span><h2>Vamos montar seu Equilibra</h2><p class="intro">Leva menos de um minuto. Você poderá alterar tudo depois.</p><div class="progress"><span style="width:60%"></span></div><form id="onboardForm"><div class="field"><label>Como podemos chamar você?</label><input name="name" value="${state.name}" placeholder="Seu nome" required></div><div class="field"><label>Qual é sua renda mensal?</label><input name="income" type="number" min="0" step="0.01" value="${state.income||''}" placeholder="R$ 0,00" required></div><div class="field"><label>Em que dia você recebe?</label><input name="payday" type="number" min="1" max="31" value="${state.payday}" required></div><button class="btn btn-primary">Continuar para o dashboard →</button></form>`);
 $('#onboardForm').onsubmit=e=>{e.preventDefault();const d=new FormData(e.target);state.name=d.get('name');state.income=Number(d.get('income'));state.payday=Number(d.get('payday'));save();closeDrawer();toast('Seu Equilibra está pronto!')}
}
function openIncome(){openDrawer(`<span class="eyebrow dark">Renda</span><h2>Editar renda mensal</h2><p class="intro">O saldo disponível será recalculado automaticamente.</p><form id="incomeForm"><div class="field"><label>Valor da renda</label><input name="income" type="number" min="0" step="0.01" value="${state.income||''}" required></div><div class="field"><label>Dia do recebimento</label><input name="payday" type="number" min="1" max="31" value="${state.payday}" required></div><button class="btn btn-primary">Salvar alterações</button></form>`);$('#incomeForm').onsubmit=e=>{e.preventDefault();const d=new FormData(e.target);state.income=Number(d.get('income'));state.payday=Number(d.get('payday'));save();closeDrawer();toast('Renda atualizada')}}
function openProfile(){openDrawer(`<span class="eyebrow dark">Perfil</span><h2>Seus dados</h2><p class="intro">Personalize como o Equilibra conversa com você.</p><form id="profileForm"><div class="field"><label>Nome de exibição</label><input name="name" value="${state.name}" required></div><button class="btn btn-primary">Salvar nome</button></form>`);$('#profileForm').onsubmit=e=>{e.preventDefault();state.name=new FormData(e.target).get('name');save();closeDrawer();toast('Nome atualizado')}}
function expenseForm(item={}){return `<span class="eyebrow dark">Despesas</span><h2>${item.id?'Editar':'Nova'} despesa</h2><p class="intro">Preencha o que souber. Forma de pagamento e observações são opcionais.</p><form id="expenseForm"><div class="field"><label>Nome da despesa</label><input name="name" value="${item.name||''}" required></div><div class="form-row"><div class="field"><label>Valor</label><input name="value" type="number" min="0" step="0.01" value="${item.value||''}" required></div><div class="field"><label>Categoria</label><select name="category">${state.categories.map(c=>`<option ${c===item.category?'selected':''}>${c}</option>`).join('')}</select></div></div><div class="form-row"><div class="field"><label>Vencimento</label><input name="due" type="date" value="${item.due||''}"></div><div class="field"><label>Data do pagamento</label><input name="payment" type="date" value="${item.payment||''}"></div></div><div class="form-row"><div class="field"><label>Status</label><select name="status"><option value="pending">Pendente</option><option value="paid" ${item.status==='paid'?'selected':''}>Pago</option></select></div><div class="field"><label>Tipo</label><select name="type"><option value="single">Única</option><option value="recurring" ${item.type==='recurring'?'selected':''}>Recorrente</option></select></div></div><div class="field"><label>Frequência da recorrência</label><select name="frequency"><option>Mensal</option><option>Semanal</option><option>Anual</option></select></div><div class="field"><label>Forma de pagamento (opcional)</label><input name="method" value="${item.method||''}"></div><div class="field"><label>Observações (opcional)</label><textarea name="notes">${item.notes||''}</textarea></div><button class="btn btn-primary">Salvar despesa</button></form>`}
function openExpense(item={}){openDrawer(expenseForm(item));$('#expenseForm').onsubmit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));d.value=Number(d.value);d.id=item.id||crypto.randomUUID();if(item.id)state.expenses=state.expenses.map(x=>x.id===item.id?d:x);else state.expenses.unshift(d);save();closeDrawer();toast(item.id?'Despesa atualizada':'Despesa adicionada')}}
function openSubscription(){openDrawer(`<span class="eyebrow dark">Assinaturas</span><h2>Adicionar assinatura</h2><p class="intro">Cadastre apenas os serviços que você realmente utiliza.</p><form id="subForm"><div class="field"><label>Nome</label><input name="name" required></div><div class="form-row"><div class="field"><label>Valor</label><input name="value" type="number" min="0" step="0.01" required></div><div class="field"><label>Categoria</label><select name="category">${state.categories.map(c=>`<option>${c}</option>`).join('')}</select></div></div><div class="form-row"><div class="field"><label>Periodicidade</label><select name="period"><option>Mensal</option><option>Anual</option></select></div><div class="field"><label>Próxima cobrança</label><input name="next" type="date"></div></div><button class="btn btn-primary">Salvar assinatura</button></form>`);$('#subForm').onsubmit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));d.value=Number(d.value);d.id=crypto.randomUUID();d.active=true;state.subscriptions.unshift(d);save();closeDrawer();toast('Assinatura adicionada')}}
function openCategory(){openDrawer(`<span class="eyebrow dark">Categorias</span><h2>Criar categoria</h2><p class="intro">Organize seus gastos do seu jeito.</p><form id="catForm"><div class="field"><label>Nome da categoria</label><input name="name" required></div><button class="btn btn-primary">Criar categoria</button></form><div class="field"><label>Categorias atuais</label><p>${state.categories.join(' · ')}</p></div>`);$('#catForm').onsubmit=e=>{e.preventDefault();const n=new FormData(e.target).get('name').trim();if(n&&!state.categories.includes(n))state.categories.push(n);save();closeDrawer();toast('Categoria criada')}}

function render(){const total=state.expenses.reduce((a,e)=>a+Number(e.value),0),subs=state.subscriptions.filter(s=>s.active).reduce((a,s)=>a+Number(s.value)/(s.period==='Anual'?12:1),0),balance=state.income-total-subs;$('#displayName').textContent=state.name||'vamos começar';$('#incomeValue').textContent=state.income?money(state.income):'—';$('#incomeHint').textContent=state.income?`Recebimento no dia ${state.payday}`:'Informe sua renda para começar';$('#expenseTotal').textContent=money(total);$('#expenseHint').textContent=state.expenses.length?`${state.expenses.length} registro${state.expenses.length>1?'s':''} no período`:'Nenhuma despesa cadastrada';$('#subscriptionTotal').textContent=money(subs);$('#subscriptionHint').textContent=state.subscriptions.length?`${state.subscriptions.length} assinatura${state.subscriptions.length>1?'s':''}`:'Nenhuma assinatura cadastrada';$('#balanceValue').textContent=state.income?money(balance):'—';
 const list=$('#expenseList');if(!state.expenses.length)list.innerHTML=`<div class="empty-icon">↗</div><h4>Você ainda não cadastrou nenhuma despesa</h4><p>Adicione um gasto para começar a acompanhar seu mês.</p>`,list.className='empty';else{list.className='';list.innerHTML=state.expenses.map(e=>`<div class="expense-row ${e.status==='paid'?'paid':''}"><div><strong>${e.name}</strong><small>${e.category} · ${e.status==='paid'?'Pago':'Pendente'}</small></div><div class="amount"><strong>${money(e.value)}</strong><small>${e.due||'Sem vencimento'}</small></div><div class="row-actions"><button title="Marcar como paga" data-pay="${e.id}">✓</button><button title="Editar" data-edit="${e.id}">✎</button><button title="Duplicar" data-copy="${e.id}">⧉</button><button title="Excluir" data-delete="${e.id}">×</button></div></div>`).join('')}
 const cats={};state.expenses.forEach(e=>cats[e.category]=(cats[e.category]||0)+Number(e.value));const entries=Object.entries(cats);$('#chartEmpty').classList.toggle('hidden',!!entries.length);$('#chartData').classList.toggle('hidden',!entries.length);if(entries.length){const colors=['#45e0a8','#8a7dff','#f6c65b','#ef7d78','#63a8ff','#82918c'];let at=0;const grad=entries.map(([k,v],i)=>{const start=at;at+=v/total*100;return `${colors[i%colors.length]} ${start}% ${at}%`}).join(',');$('#bigDonut').style.background=`conic-gradient(${grad})`;$('#legend').innerHTML=entries.map(([k,v],i)=>`<div class="legend-item"><span class="legend-dot" style="background:${colors[i%colors.length]}"></span>${k} · ${money(v)}</div>`).join('')}
 $$('[data-pay]').forEach(b=>b.onclick=()=>{const e=state.expenses.find(x=>x.id===b.dataset.pay);e.status=e.status==='paid'?'pending':'paid';save()});$$('[data-edit]').forEach(b=>b.onclick=()=>openExpense(state.expenses.find(x=>x.id===b.dataset.edit)));$$('[data-copy]').forEach(b=>b.onclick=()=>{const e=state.expenses.find(x=>x.id===b.dataset.copy);state.expenses.unshift({...e,id:crypto.randomUUID(),name:`${e.name} (cópia)`});save();toast('Despesa duplicada')});$$('[data-delete]').forEach(b=>b.onclick=()=>{state.expenses=state.expenses.filter(x=>x.id!==b.dataset.delete);save();toast('Despesa excluída')})}

$$('[data-income]').forEach(b=>b.onclick=openIncome);$$('[data-edit-profile]').forEach(b=>b.onclick=openProfile);$$('[data-expense]').forEach(b=>b.onclick=()=>openExpense());$$('[data-subscription]').forEach(b=>b.onclick=openSubscription);$$('.nav-item').forEach(b=>b.onclick=()=>{if(b.dataset.view==='expenses')openExpense();if(b.dataset.view==='subscriptions')openSubscription();if(b.dataset.view==='categories')openCategory();if(b.dataset.view==='settings')openProfile();});render();
